Repository JoeyTadisa/Excursion-Management, pull requests merged in 2021-11, with the labels that each got.

#15 Created pull_request_template.md
  pull_request_template.md
Labels: documentation

#20 Web
  project/web/frontend/src/App.css
  project/web/frontend/src/App.js
  project/web/frontend/src/LoggedInView.js
  project/web/frontend/src/LoginForm.js
  project/web/frontend/src/stores/ExcursionData.js
Labels: enhancement

#23 fix:internal-server-error resolved
  project/api/thu-excursion/src/main/java/com/thuexcursion/crud/model/Excursion.java
  project/api/thu-excursion/src/main/java/com/thuexcursion/crud/repository/ExcursionRepository.java
  project/database/bdbarmr9bpoyjedn4yyi v4.sql
  project/database/bdbarmr9bpoyjedn4yyi.sql
Labels: bug, api

#24 Web
  .gitattributes
  .gitignore
  project/web/frontend/node_modules/.cache/.eslintcache
  project/web/frontend/public/index.html
  project/web/frontend/public/logo192.png
  project/web/frontend/public/logo512.png
  project/web/frontend/public/manifest.json
  project/web/frontend/src/App.css
  project/web/frontend/src/ExcursionForm.js
  project/web/frontend/src/Excursions/ExcursionDate.css
  project/web/frontend/src/Excursions/ExcursionDate.js
  project/web/frontend/src/Excursions/ExcursionFilter.css
  project/web/frontend/src/Excursions/ExcursionFilter.js
  project/web/frontend/src/Excursions/ExcursionForm.js
  project/web/frontend/src/Excursions/ExcursionItem.css
  project/web/frontend/src/Excursions/ExcursionItem.js
  project/web/frontend/src/Excursions/ExcursionList.css
  project/web/frontend/src/Excursions/ExcursionList.js
  project/web/frontend/src/InputField.js
  project/web/frontend/src/LoggedInView.js
  project/web/frontend/src/LoginForm.js
  project/web/frontend/src/NewExcursionEntry.js
  project/web/frontend/src/SubmitButton.js
  project/web/frontend/src/UI/Card.css
  project/web/frontend/src/UI/Card.js
  project/web/frontend/src/index.js
  project/web/frontend/src/logo.svg
  project/web/frontend/src/stores/ExcursionDataStore.js
  project/web/frontend/src/stores/UserStore.js
Labels: documentation, enhancement

#25 Added ExcursionsList.js/css and modified the rest of the files accord…
  project/web/frontend/src/Excursions/ExcursionDate.js
  project/web/frontend/src/Excursions/ExcursionFilter.css
  project/web/frontend/src/Excursions/ExcursionFilter.js
  project/web/frontend/src/Excursions/ExcursionForm.js
  project/web/frontend/src/Excursions/ExcursionItem.css
  project/web/frontend/src/Excursions/ExcursionItem.js
  project/web/frontend/src/Excursions/ExcursionList.js
  project/web/frontend/src/Excursions/ExcursionsList.css
  project/web/frontend/src/Excursions/ExcursionsList.js
  project/web/frontend/src/LoggedInView.js
Labels: documentation, enhancement

#27 Added spring test dependancy to the pom file and updated AdminController test
  project/api/thu-excursion/pom.xml
  project/api/thu-excursion/src/test/java/com/thuexcursion/crud/AdminControllerLayerTest.java
Labels: enhancement, unittest, api

#29 Added new ExcursionsDetailed Views
  project/web/frontend/src/App.css
  project/web/frontend/src/App.test.js
  project/web/frontend/src/Excursions/ExcursionDate.js
  project/web/frontend/src/Excursions/ExcursionDetailedItem.css
  project/web/frontend/src/Excursions/ExcursionDetailedItem.js
  project/web/frontend/src/Excursions/ExcursionFilter.js
  project/web/frontend/src/Excursions/ExcursionForm.js
  project/web/frontend/src/Excursions/ExcursionItem.js
  project/web/frontend/src/Excursions/ExcursionList.js
  project/web/frontend/src/Excursions/ExcursionsDetailedList.css
  project/web/frontend/src/Excursions/ExcursionsDetailedList.js
  project/web/frontend/src/Excursions/ExcursionsList.js
  project/web/frontend/src/LoggedInView.js
  project/web/frontend/src/LoginForm.js
Labels: documentation, enhancement

#26 Update contributing.md
  contributing.md
Labels: documentation

#43 Fix/destination column added
  project/api/thu-excursion/src/main/java/com/thuexcursion/crud/model/Excursion.java
  project/api/thu-excursion/src/main/java/com/thuexcursion/crud/repository/ExcursionRepository.java
Labels: api

#45 Replaced user-based models with a single User model, service, repository and controller.
  project/api/thu-excursion/src/main/java/com/thuexcursion/crud/SpringBootThuexcursionCrudApplication.java
  project/api/thu-excursion/src/main/java/com/thuexcursion/crud/controller/AdminController.java
  project/api/thu-excursion/src/main/java/com/thuexcursion/crud/controller/ExcursionController.java
  project/api/thu-excursion/src/main/java/com/thuexcursion/crud/controller/OrganizerController.java
  project/api/thu-excursion/src/main/java/com/thuexcursion/crud/controller/UserController.java
  project/api/thu-excursion/src/main/java/com/thuexcursion/crud/model/Organizer.java
  project/api/thu-excursion/src/main/java/com/thuexcursion/crud/model/Student.java
  project/api/thu-excursion/src/main/java/com/thuexcursion/crud/model/User.java
  project/api/thu-excursion/src/main/java/com/thuexcursion/crud/repository/AdminRepository.java
  project/api/thu-excursion/src/main/java/com/thuexcursion/crud/repository/OrganizerRepository.java
  project/api/thu-excursion/src/main/java/com/thuexcursion/crud/repository/StudentRepository
  project/api/thu-excursion/src/main/java/com/thuexcursion/crud/repository/UserRepository.java
  project/api/thu-excursion/src/main/java/com/thuexcursion/crud/service/AdminService.java
  project/api/thu-excursion/src/main/java/com/thuexcursion/crud/service/OrganizerService.java
  project/api/thu-excursion/src/main/java/com/thuexcursion/crud/service/UserService.java
  project/api/thu-excursion/src/test/java/com/thuexcursion/crud/AdminControllerLayerTest.java
  project/database/user.sql
Labels: documentation, enhancement, api

#47 Implemented ListView, added 3 classes, ExcursionEntry to be able to P…
  project/THUExcursionApp/app/.classpath
  project/THUExcursionApp/app/.project
  project/THUExcursionApp/app/.settings/org.eclipse.buildship.core.prefs
  project/THUExcursionApp/app/build.gradle
  project/THUExcursionApp/app/src/main/AndroidManifest.xml
  project/THUExcursionApp/app/src/main/java/com/teamfive/thuexcursionapp/ExcursionDetails.java
  project/THUExcursionApp/app/src/main/java/com/teamfive/thuexcursionapp/ExcursionEntry.java
  project/THUExcursionApp/app/src/main/java/com/teamfive/thuexcursionapp/ExcursionList.java
  project/THUExcursionApp/app/src/main/java/com/teamfive/thuexcursionapp/MainActivity.java
  project/THUExcursionApp/app/src/main/res/layout/excursion_details.xml
  project/THUExcursionApp/app/src/main/res/layout/excursion_list.xml
  project/THUExcursionApp/app/src/main/res/xml/network_security_config.xml
Labels: enhancement, android
